### ISSUE TITLE
Spurious "error during reset" at random

### ISSUE THREAD

**Issue by compucat** [Ownasaurus/TAStm32#10]
Sometimes after killing a run, tastm32.py will return "error during reset" repeatedly until you either (a) get lucky or (b) powercycle the hardware. dwangoAC duplicated the issue on stream by accident. Probably just an edge case in the comms between tastm32 and the python script

**Comment by Ownasaurus** [comment]
Do you know if he had updated to the latest version?

**Comment by compucat** [comment]
Not certain, but I experienced it on latest myself.

**Comment by Ownasaurus** [comment]
The function to process serial packets is a state machine which processes one byte at a time and keeps track of its state. It was done this way just in case the serial data packets were split at an unexpected location.
The reported problem would probably occur if input ends unexpectedly. One potential solution would be to have a "timeout/reset" period of say... 0.5 seconds where if input stops, it should reset its state to being ready for a new serial command. This could be implemented either by counting cycles or using a hardware timer with interrupts. Feel free to implement this yourself if you'd like. If not, I can hopefully get to it in the near future.

**Comment by compucat** [comment]
I'll write a quick patch, but I won't have hardware to test on until I return from travel.

**Comment by Ownasaurus** [comment]
A similar or related error: COM port in use occurs seemingly randomly between runs
