### ISSUE TITLE
Stuttering at high data rate on some USB controllers

### ISSUE THREAD

**Issue by compucat** [Ownasaurus/TAStm32#11]
Audio streaming fails and stutters horribly on Ryzen's native USB controller. This likely applies to some other USB controllers, too; Intel's controllers notably work just fine.
This also likely applies to other high-data-rate payloads; we should test videophone.

This is NOT a tastm32-specific issue; it was also reproduced on total's PSoC5 board, which also relies on USB-CDC serial.

This could likely be fixed by directly using USB isochronous transfers instead of USB-CDC serial. USB serial relies on USB bulk transfers, which guarantee data transfer but not latency. Isochronous transfers are regularly scheduled and guarantee latency over completeness of data transfer. For streaming audio/video, consistent latency is more important; the problematic USB controller(s) might be pausing on some bulk transfers weirdly.

**Comment by Ownasaurus** [comment]
Closing since this is just n=1 and not specific to the tastm32 hardware. Really seems like an issue with Ryzen.
