### ISSUE TITLE
Soft Reset Transitions broken at HEAD 165a556666a038a09f581ebf392f1f8c8422c087

### ISSUE THREAD

**Issue by TheMas3212** [Ownasaurus/TAStm32#36]
Test case Super Mario World 96 exit WIP requires a soft reset at frame 1117 (r16m can be provided via dm)
this works on commit 372cd6142d27206ca348e56b181491f0794b47e8 with the command:
`./tastm32.py --console snes --players 1,2,5,6 --blank 0 --softreset --transition 1117 S 96wip.r16m`
however it fails on HEAD at 165a556666a038a09f581ebf392f1f8c8422c087
and on 8335dce6078db1fd34c518df924a76e776369c17
trying the `--nobulk` flag at the suggestion of @Ownasaurus did not help

normally works with a reset on frame 1117, fails to create the save unless reset is at 1135
save is created with the reset at 1135 however it drops a number of inputs and gets stuck at the following title screen

**Comment by Ownasaurus** [comment]
Upon further investigation, it appears that the reset pin was originally switched to push-pull so the pin would work with a power replay. It also works with the consoles well enough -- or so we thought. I guess it throws off tight timing resets. Need some time to consider our options. The power replay control won't work anymore if we make it OD again.

The best solution I've thought of thus far is to revert back to OD to restore NES/SNES power functionality... then add an external pullup to my my power relay circuit to allow it to still function. Hope to make a decision to resolve this soon.

**Comment by Ownasaurus** [comment]
Of interest is the fact that analogic logic analysis shows that the pins goes from high to low and vice versa in about 100ns in either case. However, in PP mode, the pin is held at 3v3 instead of its suspected 5v. While this still works, it may be doing some funky things to the console, ruining timings and possibly more.

**Comment by Ownasaurus** [comment]
Resolved in commit 16e3e23
