### ISSUE TITLE
Case Modification Suggestion - Make top fit only when aligned correctly

### ISSUE THREAD

**Issue by ViGrey** [Ownasaurus/TAStm32#45]
The top of the case for v3 of the TAStm32 has a special markings to indicate P1, P2, V1, and V2, making the top 1-way, but the case can still be closed even if the top of the case is rotated 180 degrees.

I personally suggest placing a notch on one side of the top part of the case and a bump that fits into the notch on the bottom part of the case so the case can only be closed correctly.

**Comment by Ownasaurus** [comment]
Just a status update so you know I didn't forget about you -- a test candidate for the version 4 case is being printed as we speak, The new (albeit similar) design can no longer be accidentally put together backwards.

**Comment by Ownasaurus** [comment]
Since v4 has a screen and buttons which are not centered on the PCB, the new top half of the case will only fit on one way.

**Comment by Ownasaurus** [comment]
Will be resolved by #57

**Comment by Ownasaurus** [comment]
Resolved by #57.
