### ISSUE TITLE
Potential protocol discrepancy for command `C`

### ISSUE THREAD

**Issue by compucat** [Ownasaurus/TAStm32#61]
Noticed something while looking over the protocol....a `C` received could be either of these:

`'A' - 'D': Feeds the configured run with a single frame of new data. See below for details`

`'C': Controller mode (no buffer, repeat last input on underrun)`

How does TAStm32 handle this?

**Comment by Ownasaurus** [comment]
After 2 years, I think you deserve a typed-out thoughtful answer.

Poorly.

The thing is, the TAStm32 itself never ended up supporting more than 1 simultaneous run. So the TAStm32 doesn't accept anything other than the A prefix.

The two choices are to either:
1) Update the protocol to only support 1 run, or
2) Change the byte for controller mode

Probably option 2 is the preferable choice. Just need to make sure all the dependent scripts are updated too
