### ISSUE TITLE
Are there similar tools for other consoles?

### ISSUE THREAD

**Issue by kraftydevil** [Ownasaurus/TAStm32#62]
Specifically I'd like to record movements on a PS5 and play them back.

My apologies for crashing the issues section here. I'm just not sure of the terminology for this type of thing and I figured you guys might be able to point me to the right place for doing this on modern consoles.

**Comment by Ownasaurus** [comment]
No problem. I wish I knew the answer. However, I am unaware of such replay devices' existence. 
Feel free to join https://discord.tas.bot/ and ask around.
